import sqlite3
conn = sqlite3.connect('rpg_db.sqlite3')
import os 
os.listdir()
query ='SELECT * FROM charactercreator_character;'
curs = conn.cursor()
len(curs.execute(query).fetchall())
curs.close()
conn.commit()
curs2 = conn.cursor()
len(curs2.execute('SELECT * FROM charactercreator_cleric;').fetchall())
curs2.close()
conn.commit()
curs21 = conn.cursor()
len(curs21.execute('SELECT * FROM charactercreator_fighter;').fetchall())
curs21.close()
conn.commit()
curs22 = conn.cursor()
len(curs22.execute('SELECT * FROM charactercreator_mage;').fetchall())
curs22.close()
conn.commit()
curs23 = conn.cursor()
len(curs23.execute('SELECT * FROM charactercreator_necromancer;').fetchall())
curs23.close()
conn.commit()
curs24 = conn.cursor()
len(curs24.execute('SELECT * FROM charactercreator_thief;').fetchall())
curs24.close()
conn.commit()
curs3 = conn.cursor()
len(curs3.execute('SELECT * FROM charactercreator_character_inventory;').fetchall())
curs3.close()
conn.commit()
curs4 = conn.cursor()
weapon_number = len(curs4.execute('SELECT * FROM armory_weapon;').fetchall())
weapon_number
curs4.close()
conn.commit()
curs42 = conn.cursor()
not_weapon_number = len(curs42.execute('SELECT * FROM armory_item;').fetchall()) - weapon_number
not_weapon_number
curs42.close()
conn.commit()
curs5 = conn.cursor()
curs5.execute('SELECT COUNT(character_id) FROM charactercreator_character_inventory GROUP BY character_id LIMIT 20;').fetchall()
